const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   INCREMEMNT_QUEUE_INDEX: "INCREMEMNT_QUEUE_INDEX:",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
   RESET_QUEUE: "RESET_QUEUE",
   STORE_EDITABLE_CARD: "STORE_EDITABLE_CARD",
   UPDATE_CREATABLE_CARD: "UPDATE_CREATABLE_CARD",
   UPDATE_QUEUED_CARDS: "UPDATE_QUEUED_CARDS",
};

export default actions;
